### ISSUE TITLE
Chapter 5.2 Event Modifiers

### ISSUE THREAD

**Issue by mdeprezzo** [hootlex/the-majesty-of-vuejs#20]
Hi guys, thanks for the book. It's amazing!!
But i notice that, if i try to attach **stop** to the **@click=".."**, in the calculator example, the page continues to reloading after the button is clicked. Works only if i use **prevent**. I tried with vue 1.0.24 and with the last release 1.0.26. Maybe could be a browser version problem ? I'm using chrome 54.0.2840.34 beta-m

**Comment by pongoman** [comment]
Hello, happy to hear that.
If you attach .stop the event's propagation will be stopped (stopPropagation stops the event from bubbling up the event chain) but the form still submits because thats event default behavior and the page still reloads. 
This might [help.](http://stackoverflow.com/questions/5963669/whats-the-difference-between-event-stoppropagation-and-event-preventdefault) Thanks for taking some time to open an issue.

**Comment by mdeprezzo** [comment]
Oh, right! Sorry! I'm not so good yet, in JavaScript. :D. Thanks again for
thia book

Il 25/Set/2016 15:52, "Kostas Maniatis" notifications@github.com ha
scritto:
